<?php

namespace Src\RegistrationService\Checkers;

use App\Models\Referral;
use Src\RegistrationService\Checker;
use Src\RegistrationService\RegistrationRequest;

class ReferralChecker extends Checker
{
    public function check(RegistrationRequest $request): bool
    {
        if (!$this->IsReferralValid($request->getReferralCode())) {
            return false;
        }

        return parent::check($request); // TODO: Change the autogenerated stub
    }

    private function IsReferralValid(string $referralCode)
    {
        Referral::query()->where('code', $referralCode)->count() > 0;
    }
}
