<?php

namespace Src\RegistrationService\Checkers;

use Src\RegistrationService\Checker;
use Src\RegistrationService\RegistrationRequest;

class UserPasswordChecker extends Checker
{

    public function check(RegistrationRequest $request): bool
    {
        if (!$this->isPasswordValid($request->getPassword())) {
            return false;
        }

        return parent::check($request); // TODO: Change the autogenerated stub
    }

    private function isPasswordValid(string $password): bool
    {
        return true;
    }
}
