<?php

namespace Src\RegistrationService\Checkers;

use App\Models\User;
use Carbon\Carbon;
use Src\RegistrationService\Checker;
use Src\RegistrationService\RegistrationRequest;

class UserEmailChecker extends Checker
{
    public function check(RegistrationRequest $request): bool
    {
        if ($this->emailExists($request->getEmailAddress())) {
            return false;
        }

        return parent::check($request); // TODO: Change the autogenerated stub
    }

    private function emailExists(string $emailAddress): bool
    {
        return User::query()->where('email', $emailAddress)->count() > 0;
    }
}
